name: vehicle_consumption_calculator
description: A lightweight application for convenient monitoring of energy expenses for your car.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  intl: any
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true 
  uses-material-design: true
  fonts:
    - family: GillSans
      fonts:
        - asset: lib/presentation/fonts/GillSans.ttc
    - family: Segment7Standard
      fonts:
        - asset: lib/presentation/fonts/Segment7Standard.otf

