name: vehicle_consumption_calculator
description: A lightweight application for convenient monitoring of energy expenses for your car.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: 
  flex_color_scheme: 
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 
  intl: 
  meta: 
  shared_preferences: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter:
  generate: true 
  uses-material-design: true
  fonts:
    - family: GillSans
      fonts:
        - asset: assets/fonts/GillSans.ttc
    - family: Segment7Standard
      fonts:
        - asset: assets/fonts/Segment7Standard.otf

